version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/app/src
    ports:
        - "3000:3000"
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/src:/app/src
    ports:
      - "5000:5000"
